base_url = "https://flame.csail.mit.edu"
compile_sass = true
build_search_index = false
author = "Rachit Nigam"

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[link_checker]
internal_level = "warn"
external_level = "warn"
